### ISSUE TITLE
Wiki?

### ISSUE THREAD

**Issue by gaebel** [s0563858/MA_Projekt#15]
Sollten wir im Wiki festhalten, wie der Code zusammenhängt und wo man bestimmte Funktionen findet?

**Comment by sneakfax** [comment]
Hm, könnte man - oder wir machen es in dem readme(sonst haben vielleicht zu viele orte wo informationen abgelegt sind - dann ist vielleicht alles nicht so verstreut) - aber wenn du möchtest können wir es auch mit wiki probieren - wäre egtl auch nicht schlecht😃
