### ISSUE TITLE
Android, Desktop, Web App

### ISSUE THREAD

**Issue by gaebel** [s0563858/MA_Projekt#18]
@s0563858 Kann es sein dass das Game auf Android, Desktop und im Browser läuft? Wegen den 3 Launchern. Desktop compiled bei mir nicht und mit HTML kann ich (noch) nichts anfangen. Main Logik ist bei Core, wo befindet sich der Code für das Layout?

**Comment by sneakfax** [comment]
Es läuft mindestens auf dem dekstop und auf andoid - ich habe zum entwickeln ein framework „libgdx“ verwendet - es ermöglicht egtl. plattformunabhängige entwicklung

**Comment by sneakfax** [comment]
Zu der projektstruktur schreibe ich gleich was bei readmerein
