### ISSUE TITLE
Choose data storage option

### ISSUE THREAD

**Issue by gaebel** [s0563858/MA_Projekt#2]
Ich würde die Persistierung des Highscores und der letzten x,y Position folgendermaßen umsetzen: https://developer.android.com/reference/android/content/SharedPreferences.html

**Comment by gaebel** [comment]
@s0563858 was hältst du davon?

**Comment by sneakfax** [comment]
@jgaeb ja die funktionen sind einfach zu verwenden, find ich gut👍🏼
