### ISSUE TITLE
implement multiplayer

### ISSUE THREAD

**Issue by sneakfax** [s0563858/MA_Projekt#20]

**Comment by gaebel** [comment]
`import java.io.*;
import java.net.*;

class Client {
    private static int playerYPos = 0;
    private static int pipeXPos = 0;
    private static boolean hasEnded = false;
    private static int ID;

    public static void main(String[] args) {
        try {
            System.out.println("[Client] Connecting to Server...");
            ID = Integer.valueOf(communicateWithServer(""));

            while(!hasEnded) {
                System.out.println("[Client] Sending data to Server");
                String response = communicateWithServer("posY=" + playerYPos + "&id=" + ID);
                System.out.println("[Client] Received data from Server: " + response);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }


    public static String communicateWithServer(String parameters) throws IOException {
        HttpURLConnection connection;
        PrintWriter out;
        BufferedReader in;
        String line;
        String player = String.valueOf(playerYPos);

        URL addr = new URL("http://localhost:8080/app?" + parameters);
        System.out.println(addr);
        connection = (HttpURLConnection) addr.openConnection();
        connection.setRequestMethod("GET");
        connection.setRequestProperty("Content-Type", "application/x-www-form-urlencoded");

        connection.setUseCaches(false);
        connection.setDoOutput(true);

        out = new PrintWriter(connection.getOutputStream());
        in = new BufferedReader(new InputStreamReader(connection.getInputStream()));

        line = in.readLine();
        in.close();

        if(!parameters.isEmpty()) {
            out.println(player + "," + ID);
            out.flush();
            out.close();
        } else {
            System.out.println("[Client] Received ID[" + line + "] from Server");
        }

        return line;
    }
}`
